modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC0-1.0"
issueTrackerURL = "https://github.com/NikitaCartes/DisableInsecureChatToast/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://github.com/NikitaCartes/DisableInsecureChatToast"
authors = "NikitaCartes"
description = '''
Deletes the warning toast about connecting to a server without enforced secure chat.
'''

[[mixins]]
config = "disableinsecurechattoast.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "CLIENT"
